name: just_play_test
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #UI
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.0+1
  dismissible_page: ^1.0.2


  # Logic
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  http: ^0.13.6
  intl: ^0.18.1
    
  #Firebase
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.1
  google_sign_in: ^5.4.2
  firebase_auth: ^4.3.0

  #Console
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/static/img/
    - assets/static/json/

flutter_icons:
  android: "justplay"
  ios: false
  remove_alpha_ios: true
  image_path: "assets/static/img/logo_just_play.png"
  min_sdk_android: 21
